---

- hosts: all
  become: true
  tasks:

  - name: Backup Bashrc With owners permissions
    copy:
      src: /home/eddy/.bashrc
      dest: /home/eddy/.bashrc.bak
      owner: eddy
      group: eddy
      mode: '0644'

  - name: Reading The Content of Alias File
    slurp:
      src: Alias_file
    register: Alias_Content

  - name: Adding Alias File Content To Bashrc
    lineinfile:
      path: /home/eddy/.bashrc
      line: Alias_Content.stdout_lines
      state: present
      create: yes
