---

- hosts: all
  become: true
  tasks:

  - name: Backup Bashrc With owners permissions
    copy:
      src: /home/eddy/.bashrc
      dest: /home/eddy/.bashrc.bak
      owner: eddy
      group: eddy
      mode: '0644'

  - name: This command will change the working directory to somedir/ and will only run when somedir/somelog.txt doesn't exist.
    command:
      cmd: "cat Alias_file >> /home/eddy/.bashrc"
    args:
      chdir: somedir/
